### ISSUE TITLE
Cannot open locally hosted pages in XRviewer whiled developing.

### ISSUE THREAD

**Issue by JakeJustLearning** [mozilla-mobile/webxr-ios-js#113]
I am trying to use XR viewer to do development for WebXR and three js. When I start a local host HTTPS server for development I can connect on chrome by going to `https://<ip>:<port>`, but the XR viewer on iOS cannot open the page. currently I have been having to push every change to GitHub pages and it makes the development process really slow. Is this a known issue? is there anyway to get around this to use XR viewer to access a locally hosted dev instance?

**Comment by camjackson** [comment]
@JakeJustLearning I believe it's because the app is missing the `NSLocalNetworkUsageDescription` permission. Local network access requires special permission on iOS, but the XR viewer app doesn't ask for it, so the network calls just fail. It should be a really easy fix, but I haven't been able to figure out where the code for the app is located, or who is maintaining it.
